{
    "name": "VivaFarm Petty Cash",
    "version": "19.0.1.0.0",
    "summary": "Petty cash fund and voucher management with TFRS for SMEs compliance",
    "description": "Custodian-based petty cash float with voucher tracking, top-up wizard, and monthly replenishment wizard. Posts sub-ledger to dedicated Petty Cash account (111102) with variance account (639900).",
    "author": "VivaFarm",
    "category": "Accounting",
    "depends": ["account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/wizard_views.xml",
        "views/fund_views.xml",
        "views/voucher_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
    "license": "LGPL-3",
}
